export {
	CODEX_CONFIG_SCHEMA_COMMENT,
	CODEX_CONFIG_SCHEMA_URL,
	CONTEXT7_DASHBOARD_URL,
	LINE_BREAK_PATTERN,
	OAL_CODEX_BASE_INSTRUCTIONS_FILE,
	OAL_CODEX_HOOKS_DIR,
	OAL_CODEX_MODEL_INSTRUCTIONS_RELATIVE,
	OAL_OPENCODE_HOOKS_DIR,
	POSITIVE_INTEGER_PATTERN,
	RTK_INSTALL_SCRIPT_URL,
} from "@openagentlayer/source";

export const CODEX_COLOR_FIELD_PATTERN = /^color\s*=/m;
export const HEX_COLOR_FRAGMENT_PATTERN = /#[0-9a-f]{6}/;
export const HEX_COLOR_VALUE_PATTERN = /^#[0-9a-f]{6}$/;
export const CHECKED_CHECKBOX_LINE_PATTERN = /^- \[x\] /gm;
export const ROADMAP_CHECKBOX_PATTERN = /^- \[[ x]\] /;
